version: "3"

# Advanced Networking: Secondary Pi-hole + Unbound Resolver
# Provides redundancy and private DNS resolving (no upstream tracking).

services:
  pihole_zapas:
    container_name: pihole_zapas
    image: pihole/pihole:latest
    ports:
      - "54:53/tcp"
      - "54:53/udp"
      - "8085:80/tcp"
    environment:
      TZ: 'Europe/Warsaw'
      WEBPASSWORD: 'YOUR_SECURE_PASSWORD'
      PIHOLE_DNS_: '127.0.0.1#5335' # Connects directly to the Unbound service
      DNSMASQ_LISTENING: 'all'
    volumes:
      - ./pihole_zapas/etc-pihole:/etc/pihole
      - ./pihole_zapas/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    depends_on:
      - unbound

  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    ports:
      - "5335:5335/tcp"
      - "5335:5335/udp"
    restart: unless-stopped
